---
- name: setup vprofile bastion host
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import bastion setup Variables
      include_vars: vpc_setup_vars.yml

    - name: Import VPC setup Variable
      include_vars: vpc-output_vars.yml

    - name: create vprofile ec2key
      ec2_key:
        name: vprofile-key
        region: "{{region}}"
      register: key_out
    - debug:
        var: key_out
    - name: save private key to file bastion-key.pem
      copy: 
        content: "{{key_out.key.private_key}}"
        dest: "./vprofile-key.pem"
        mode: 0600
      when: key_out.changed

    - name: create security group for bastion host
      ec2_group:
        name: bastion-host-sg
        description: allow port 22 from everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: BastionSG_out
    - debug: 
        var: BastionSG_out
    - name: Creating Bastion Host
      ec2:
        key_name: vprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Bastion_host"
          Project: Vprofile
          Owner: DevOps team
        exact_count: 1  #to make it idempotent
        count_tag:
          Name: "Bastion_host"
          Project: Vprofile
          Owner: DevOps team
        group_id: "{{BastionSG_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastionHost_out
    - debug:
        var: bastionHost_out
    
    - name: insert/update "bastionSgid" in vpc-output_vars.yml
      block in file:
        path: vpc-output_vars.yml
        block: |
          BastionSGid: {{BastionSG_out.group_id}}